/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library_management_system;
import java.sql.*;
import java.util.regex.*;
import javax.swing.JOptionPane;
import project.ConnectionProvider;

/**
 *
 * @author akm
 */
public class AddNewStudent extends javax.swing.JFrame {

    /**
     * Creates new form AddNewStudent
     */
    public AddNewStudent() {
        initComponents();
    }
    PreparedStatement pst;
    Connection con;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        m_name = new javax.swing.JTextField();
        m_email = new javax.swing.JTextField();
        m_password = new javax.swing.JPasswordField();
        m_batchNO = new javax.swing.JTextField();
        m_contact = new javax.swing.JTextField();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        m_course = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        m_branch = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        m_roll_no = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        m_fathername = new javax.swing.JTextField();
        btn_cancel = new javax.swing.JButton();
        l_email = new javax.swing.JLabel();
        l_content = new javax.swing.JLabel();
        l_name = new javax.swing.JLabel();
        l_password = new javax.swing.JLabel();
        l_fathername = new javax.swing.JLabel();
        l_batch_no = new javax.swing.JLabel();
        l_roll_no = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(227, 201, 237));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Username: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("E-mail:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Password: ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Gender: ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Batch-No:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Contact-No:");

        jButton1.setBackground(new java.awt.Color(209, 101, 24));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Register");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        m_name.setBackground(new java.awt.Color(173, 232, 193));
        m_name.setActionCommand("null");
        m_name.setSelectionColor(new java.awt.Color(255, 255, 255));
        m_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_nameActionPerformed(evt);
            }
        });
        m_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                m_nameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                m_nameKeyReleased(evt);
            }
        });

        m_email.setBackground(new java.awt.Color(173, 232, 193));
        m_email.setSelectionColor(new java.awt.Color(255, 238, 21));
        m_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                m_emailKeyReleased(evt);
            }
        });

        m_password.setBackground(new java.awt.Color(173, 232, 193));
        m_password.setSelectionColor(new java.awt.Color(255, 238, 21));
        m_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_passwordActionPerformed(evt);
            }
        });
        m_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                m_passwordKeyReleased(evt);
            }
        });

        m_batchNO.setBackground(new java.awt.Color(173, 232, 193));
        m_batchNO.setSelectionColor(new java.awt.Color(255, 238, 21));
        m_batchNO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                m_batchNOKeyReleased(evt);
            }
        });

        m_contact.setBackground(new java.awt.Color(173, 232, 193));
        m_contact.setSelectionColor(new java.awt.Color(255, 238, 21));
        m_contact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                m_contactKeyReleased(evt);
            }
        });

        jRadioButton3.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(102, 102, 102));
        jRadioButton3.setText("female");
        jRadioButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jRadioButton3.setOpaque(false);
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(102, 102, 102));
        jRadioButton2.setText("male");
        jRadioButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jRadioButton2.setOpaque(false);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        m_course.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pre-HND", "HNC", "HND", "BSC", "BSC(Honas)", "Master", "PHD" }));
        m_course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_courseActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Choose Course:");
        jLabel7.setMaximumSize(new java.awt.Dimension(66, 17));
        jLabel7.setMinimumSize(new java.awt.Dimension(66, 17));
        jLabel7.setName(""); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Choose Branch:");

        m_branch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Programming", "Networking" }));
        m_branch.setMinimumSize(new java.awt.Dimension(81, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Roll-No:");

        m_roll_no.setBackground(new java.awt.Color(173, 232, 193));
        m_roll_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                m_roll_noKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Add New Member");

        jButton2.setBackground(new java.awt.Color(209, 101, 24));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("FatherName:");

        m_fathername.setBackground(new java.awt.Color(173, 232, 193));
        m_fathername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                m_fathernameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                m_fathernameKeyReleased(evt);
            }
        });

        btn_cancel.setBackground(new java.awt.Color(209, 101, 24));
        btn_cancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/red-x-mark-transparent-background-3.png"))); // NOI18N
        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        l_email.setForeground(new java.awt.Color(102, 102, 102));

        l_content.setForeground(new java.awt.Color(102, 102, 102));

        l_name.setForeground(new java.awt.Color(102, 102, 102));

        l_password.setForeground(new java.awt.Color(102, 102, 102));

        l_fathername.setForeground(new java.awt.Color(102, 102, 102));

        l_batch_no.setForeground(new java.awt.Color(102, 102, 102));

        l_roll_no.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(70, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(46, 46, 46)
                                    .addComponent(m_fathername))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10))
                                    .addGap(26, 26, 26)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(m_branch, 0, 253, Short.MAX_VALUE)
                                        .addComponent(m_course, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(m_contact)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel5))
                                    .addGap(58, 58, 58)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(m_batchNO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(34, 34, 34)
                                            .addComponent(jRadioButton3))
                                        .addComponent(m_roll_no)
                                        .addComponent(m_password, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                                        .addComponent(m_email, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(m_name, javax.swing.GroupLayout.Alignment.LEADING))))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l_fathername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(l_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(l_content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(l_batch_no, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(l_roll_no, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(m_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(m_email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(l_email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(l_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(m_password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(l_password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(m_batchNO, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(l_batch_no, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(m_roll_no, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addComponent(l_roll_no, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(m_course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(m_branch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(m_contact, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(m_fathername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(77, 77, 77))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(l_fathername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20))))
                    .addComponent(l_content, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 570, 630));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background (2).jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String Student_username = m_name.getText();
        String Student_email = m_email.getText();
        String Student_password = m_password.getText();
        String Student_gender = gender;
        String Student_BatchNo = m_batchNO.getText();
        String Student_RollNo = m_roll_no.getText();
        String Student_Course = (String) m_course.getSelectedItem();
        String Student_Branch = (String) m_branch.getSelectedItem();
        String Student_ContentNo = m_contact.getText();
        String Student_FatherName = m_fathername.getText();
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
//            st.executeUpdate("insert into student values('" + StudentID + "','" + Student_username + "','" + Student_email + "','" + Student_password + "','" + Student_gender + "','" + Student_BatchNo + "','" + Student_RollNo + "','" + Student_Course + "','" + Student_Branch + "','" + Student_ContentNo + "','" + Student_FatherName + "')");
//            JOptionPane.showMessageDialog(null, "Successfully Added");
            if (Student_username.trim().length() == 0 || Student_username.trim().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Student Name cannot be empty");
            } else if (Student_email.trim().length() == 0 || Student_email.trim().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Student Email cannot be empty");
            } else if (Student_password.trim().length() == 0 || Student_password.trim().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Student Password be empty");
            } else if (Student_gender.trim().length() == 0 || Student_gender.trim().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Gender cannot be empty");
            } else if (Student_BatchNo.trim().length() == 0 || Student_BatchNo.trim().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "BatchNo cannot be empty");
            }else if (Student_RollNo.trim().length() == 0 || Student_RollNo.trim().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "RollNo cannot be empty");
            }else if (Student_Course.trim().length() == 0 || Student_Course.trim().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Student Course cannot be empty");
            }else if (Student_Branch.trim().length() == 0 || Student_Branch.trim().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Student Branch cannot be empty");
            }else if (Student_ContentNo.trim().length() == 0 || Student_ContentNo.trim().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "ContentNo cannot be empty");
            }else if (Student_FatherName.trim().length() == 0 || Student_FatherName.trim().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Father Name cannot be empty");
            } else {
            pst = con.prepareStatement("insert into student(Student_username,Student_email,Student_password,Student_gender,Student_BatchNo,Student_RollNo,Student_Course,Student_Branch,Student_ContentNo,Student_FatherName)values(?,?,?,?,?,?,?,?,?,?)");
            pst.setString(1, Student_username);
            pst.setString(2, Student_email);
            pst.setString(3, Student_password);
            pst.setString(4, Student_gender);
            pst.setString(5, Student_BatchNo);
            pst.setString(6, Student_RollNo);
            pst.setString(7, Student_Course);
            pst.setString(8, Student_Branch);
            pst.setString(9, Student_ContentNo);
            pst.setString(10, Student_FatherName);
            int k = pst.executeUpdate();
            if (k == 1) {
                JOptionPane.showMessageDialog(this, "Successfully Added! ");

                m_name.setText("");
                m_email.setText("");
                m_password.setText("");
                gender.isEmpty();
                m_batchNO.setText("");
                m_roll_no.setText("");
                m_course.setSelectedIndex(-1);
                m_branch.setSelectedIndex(-1);
                m_contact.setText("");
                m_fathername.setText("");

            } else {
                JOptionPane.showMessageDialog(this, "Error");
            }
            setVisible(false);
            new AddNewStudent().setVisible(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            setVisible(false);
            new AddNewStudent().setVisible(true);

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void m_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_nameActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        gender = "Female";
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void m_courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_courseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_courseActionPerformed

    private void m_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_passwordActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Main().setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        gender = "Male";
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
       
        m_name.setText("");
        m_email.setText("");
        m_password.setText("");
        gender.isEmpty();
        m_batchNO.setText("");
        m_roll_no.setText("");
        m_contact.setText("");
        m_fathername.setText("");
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void m_emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m_emailKeyReleased
        // TODO add your handling code here:
        String PATTERN = "[a-zA-Z0-9]{0,30}[@][a-zA-Z0-9]{0,10}[.][a-zA-Z]{0,5}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(m_email.getText());
        if (!match.matches()) {
            l_email.setText("Incorect!");
        } else {
            l_email.setText(null);
        }
    }//GEN-LAST:event_m_emailKeyReleased

    private void m_contactKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m_contactKeyReleased
        // TODO add your handling code here:
        String PATTERN = "[0-9]{0,12}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(m_contact.getText());
        if (!match.matches()) {
            l_content.setText("Incorect!");
        } else {
            l_content.setText(null);
        }
    }//GEN-LAST:event_m_contactKeyReleased

    private void m_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m_nameKeyReleased
        // TODO add your handling code here:
//         String PATTERN ="[a-zA-Z]+";
//        Pattern patt = Pattern.compile(PATTERN);
//        Matcher match = patt.matcher(m_name.getText());
//        if(!match.matches()){
//            l_name.setText("Incorect!");
//        }
//        else{
//            l_name.setText(null);
//        }

    }//GEN-LAST:event_m_nameKeyReleased

    private void m_fathernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m_fathernameKeyReleased
        // TODO add your handling code here:
//        String PATTERN ="[a-zA-Z0-9]{0,30}$";
//        Pattern patt = Pattern.compile(PATTERN);
//        Matcher match = patt.matcher(m_fathername.getText());
//        if(!match.matches()){
//            l_fathername.setText("Incorect!");
//        }
//        else{
//           l_fathername.setText(null);
//        }
    }//GEN-LAST:event_m_fathernameKeyReleased

    private void m_passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m_passwordKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#&()–[{}]:;',?/*~$^+=<>]).{8,20}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(m_password.getText());
        if (!match.matches()) {
            l_password.setText("Incorect!");
        } else {
            l_password.setText(null);
        }
    }//GEN-LAST:event_m_passwordKeyReleased

    private void m_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m_nameKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)) {
            m_name.setEditable(true);
            l_name.setText("Correct");
        } else {
            m_name.setEditable(false);
            l_name.setText("InCorrect");
        }
    }//GEN-LAST:event_m_nameKeyPressed

    private void m_roll_noKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m_roll_noKeyReleased
        // TODO add your handling code here:
        String PATTERN = "[0-9]{0,2}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(m_roll_no.getText());
        if (!match.matches()) {
            l_roll_no.setText("Incorect!");
        } else {
            l_roll_no.setText(null);
        }
    }//GEN-LAST:event_m_roll_noKeyReleased

    private void m_fathernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m_fathernameKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)) {
            m_fathername.setEditable(true);
            l_fathername.setText("Correct");
        } else {
            m_fathername.setEditable(false);
            l_fathername.setText("InCorrect");
        }
    }//GEN-LAST:event_m_fathernameKeyPressed

    private void m_batchNOKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m_batchNOKeyReleased
        // TODO add your handling code here:
        String PATTERN = "[B]{1}[-]{1}[0-9]{0,2}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(m_batchNO.getText());
        if (!match.matches()) {
            l_batch_no.setText("Incorect!");
        } else {
            l_batch_no.setText(null);
        }
    }//GEN-LAST:event_m_batchNOKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JLabel l_batch_no;
    private javax.swing.JLabel l_content;
    private javax.swing.JLabel l_email;
    private javax.swing.JLabel l_fathername;
    private javax.swing.JLabel l_name;
    private javax.swing.JLabel l_password;
    private javax.swing.JLabel l_roll_no;
    private javax.swing.JTextField m_batchNO;
    private javax.swing.JComboBox<String> m_branch;
    private javax.swing.JTextField m_contact;
    private javax.swing.JComboBox<String> m_course;
    private javax.swing.JTextField m_email;
    private javax.swing.JTextField m_fathername;
    private javax.swing.JTextField m_name;
    private javax.swing.JPasswordField m_password;
    private javax.swing.JTextField m_roll_no;
    // End of variables declaration//GEN-END:variables
private String gender;
}
