/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library_management_system;

/**
 *
 * @author akm
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_add_member = new javax.swing.JButton();
        btn_add_book = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btn_return_book = new javax.swing.JButton();
        btn_issue_book = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        btn_View_Students = new javax.swing.JButton();
        btn_view_books = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btn_viewRequestBook = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_add_member.setBackground(new java.awt.Color(204, 204, 204));
        btn_add_member.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_add_member.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_member.png"))); // NOI18N
        btn_add_member.setText("Add New Member");
        btn_add_member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_memberActionPerformed(evt);
            }
        });
        getContentPane().add(btn_add_member, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 200, 80));

        btn_add_book.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_add_book.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add book.png"))); // NOI18N
        btn_add_book.setText("Add New Book");
        btn_add_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_bookActionPerformed(evt);
            }
        });
        getContentPane().add(btn_add_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 200, 80));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Statics.png"))); // NOI18N
        jButton3.setText("Statistics");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 200, 80));

        btn_return_book.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_return_book.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/return book png.png"))); // NOI18N
        btn_return_book.setText("Return Book ");
        btn_return_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_return_bookActionPerformed(evt);
            }
        });
        getContentPane().add(btn_return_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 200, 80));

        btn_issue_book.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_issue_book.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/issue.png"))); // NOI18N
        btn_issue_book.setText("Issue Book");
        btn_issue_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_issue_bookActionPerformed(evt);
            }
        });
        getContentPane().add(btn_issue_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 40, 200, 80));

        btn_logout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        btn_logout.setText("Logout");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 450, 250, 90));

        btn_View_Students.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_View_Students.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view student.png"))); // NOI18N
        btn_View_Students.setText("View Students");
        btn_View_Students.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_View_StudentsActionPerformed(evt);
            }
        });
        getContentPane().add(btn_View_Students, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 200, 80));

        btn_view_books.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_view_books.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view books.png"))); // NOI18N
        btn_view_books.setText("View Books");
        btn_view_books.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_view_booksActionPerformed(evt);
            }
        });
        getContentPane().add(btn_view_books, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 180, 200, 80));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("ManageMember");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 320, 200, 80));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("ManageBook");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 200, 80));

        btn_viewRequestBook.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_viewRequestBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/issue.png"))); // NOI18N
        btn_viewRequestBook.setText("Request Book");
        btn_viewRequestBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewRequestBookActionPerformed(evt);
            }
        });
        getContentPane().add(btn_viewRequestBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 250, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background (3).jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Statistics().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn_add_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_bookActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new AddBook().setVisible(true);
    }//GEN-LAST:event_btn_add_bookActionPerformed

    private void btn_add_memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_memberActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new AddNewStudent().setVisible(true);
    }//GEN-LAST:event_btn_add_memberActionPerformed

    private void btn_View_StudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_View_StudentsActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ViewStudent().setVisible(true);
    }//GEN-LAST:event_btn_View_StudentsActionPerformed

    private void btn_view_booksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_view_booksActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ViewBook().setVisible(true);
    }//GEN-LAST:event_btn_view_booksActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_issue_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_issue_bookActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new IssueBook().setVisible(true);
    }//GEN-LAST:event_btn_issue_bookActionPerformed

    private void btn_return_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_return_bookActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ReturnBook().setVisible(true);
    }//GEN-LAST:event_btn_return_bookActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ManageMember().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ManageBook().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_viewRequestBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewRequestBookActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ViewRequestBook().setVisible(true);
    }//GEN-LAST:event_btn_viewRequestBookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_View_Students;
    private javax.swing.JButton btn_add_book;
    private javax.swing.JButton btn_add_member;
    private javax.swing.JButton btn_issue_book;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_return_book;
    private javax.swing.JButton btn_viewRequestBook;
    private javax.swing.JButton btn_view_books;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
