/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library_management_system;

import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;
import project.ConnectionProvider;

/**
 *
 * @author akm
 */
public class ManageMember extends javax.swing.JFrame {

    /**
     * Creates new form ManageMember
     */
    public ManageMember() {
        initComponents();
//        Connect();
        load_Member();
    }
    PreparedStatement pst;
    Connection con;
    ResultSet rs;

    public void load_Member() {
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from student");
            ResultSetMetaData rsd = rs.getMetaData();
            int c;
            c = rsd.getColumnCount();
            DefaultTableModel d = (DefaultTableModel) jTable1.getModel();
            d.setRowCount(0);
            while (rs.next()) {
                Vector v2 = new Vector();
                for (int i = 1; i <= c; i++) {
                    v2.add(rs.getString("StudentID"));
                    v2.add(rs.getString("Student_username"));
                    v2.add(rs.getString("Student_email"));
                    v2.add(rs.getString("Student_password"));
                    v2.add(rs.getString("Student_gender"));
                    v2.add(rs.getString("Student_BatchNo"));
                    v2.add(rs.getString("Student_RollNo"));
                    v2.add(rs.getString("Student_Course"));
                    v2.add(rs.getString("Student_Branch"));
                    v2.add(rs.getString("Student_ContentNo"));
                    v2.add(rs.getString("Student_FatherName"));

                }
                d.addRow(v2);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "error");
        }
    }

//    public void Connect()
//    {
//        try{
//            Class.forName("com.mysql.jdbc.Driver");
//            con = DriverManager.getConnection("jdbc:mysql://localhost:3308/library_management_system?useSSL=false","root","");
//            
//        }
//        catch(ClassNotFoundException ex){
//            Logger.getLogger(testing.class.getName()).log(Level.SEVERE,null,ex);
//        } catch (SQLException ex) {
//            Logger.getLogger(testing.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }   
//    public void load_Member(){
//        try{
//            pst = con.prepareStatement("select * from student");
//            rs = pst.executeQuery();
//            ResultSetMetaData rsd = rs.getMetaData();
//            int c;
//            c = rsd.getColumnCount();
//            DefaultTableModel d = (DefaultTableModel)jTable1.getModel();
//            d.setRowCount(0);
//            while(rs.next()){
//                Vector v2 = new Vector();
//                for(int i =1;i<=c;i++){
//                    v2.add(rs.getString("StudentID"));
//                    v2.add(rs.getString("Student_username"));
//                    v2.add(rs.getString("Student_email"));
//                    v2.add(rs.getString("Student_password"));
//                    v2.add(rs.getString("Student_gender"));
//                    v2.add(rs.getString("Student_BatchNo"));
//                    v2.add(rs.getString("Student_RollNo"));
//                    v2.add(rs.getString("Student_Course"));
//                    v2.add(rs.getString("Student_Branch"));
//                    v2.add(rs.getString("Student_ContentNo"));
//                    v2.add(rs.getString("Student_FatherName"));
//                    
//                }
//                d.addRow(v2);
//            }
//        }
//        catch(Exception e){
//            System.out.println(e);
//        }
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        m_name = new javax.swing.JTextField();
        m_email = new javax.swing.JTextField();
        m_password = new javax.swing.JPasswordField();
        m_batchNO = new javax.swing.JTextField();
        m_contact = new javax.swing.JTextField();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        m_course = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        m_branch = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        m_roll_no = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        m_id = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        m_fathername = new javax.swing.JTextField();
        btn_cancel = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_search = new javax.swing.JButton();
        search = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Username: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("E-mail:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Password: ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Gender: ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Batch-No:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Contact-No:");

        jButton1.setBackground(new java.awt.Color(209, 101, 24));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Register");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        m_name.setBackground(new java.awt.Color(173, 232, 193));
        m_name.setActionCommand("null");
        m_name.setSelectionColor(new java.awt.Color(255, 255, 255));
        m_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_nameActionPerformed(evt);
            }
        });

        m_email.setBackground(new java.awt.Color(173, 232, 193));
        m_email.setSelectionColor(new java.awt.Color(255, 238, 21));

        m_password.setBackground(new java.awt.Color(173, 232, 193));
        m_password.setSelectionColor(new java.awt.Color(255, 238, 21));
        m_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_passwordActionPerformed(evt);
            }
        });

        m_batchNO.setBackground(new java.awt.Color(173, 232, 193));
        m_batchNO.setSelectionColor(new java.awt.Color(255, 238, 21));

        m_contact.setBackground(new java.awt.Color(173, 232, 193));
        m_contact.setSelectionColor(new java.awt.Color(255, 238, 21));

        jRadioButton3.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton3.setText("female");
        jRadioButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jRadioButton3.setOpaque(false);
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton2.setText("male");
        jRadioButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jRadioButton2.setOpaque(false);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        m_course.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pre-HND", "HNC", "HND", "BSC", "BSC(Honas)", "Master", "PHD" }));
        m_course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_courseActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Choose Course:");
        jLabel7.setMaximumSize(new java.awt.Dimension(66, 17));
        jLabel7.setMinimumSize(new java.awt.Dimension(66, 17));
        jLabel7.setName(""); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Choose Branch:");

        m_branch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Programming", "Networking" }));
        m_branch.setMinimumSize(new java.awt.Dimension(81, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Roll-No:");

        m_roll_no.setBackground(new java.awt.Color(173, 232, 193));

        jButton2.setBackground(new java.awt.Color(209, 101, 24));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("MemberID");

        m_id.setBackground(new java.awt.Color(173, 232, 193));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("FatherName:");

        m_fathername.setBackground(new java.awt.Color(173, 232, 193));

        btn_cancel.setBackground(new java.awt.Color(209, 101, 24));
        btn_cancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/red-x-mark-transparent-background-3.png"))); // NOI18N
        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        btn_update.setBackground(new java.awt.Color(209, 101, 24));
        btn_update.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        jToggleButton1.setBackground(new java.awt.Color(209, 101, 24));
        jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jToggleButton1.setText("Delete");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(350, 380, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(m_branch, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(m_course, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(65, 65, 65)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(m_batchNO, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(jRadioButton3)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(m_password, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(m_roll_no)
                                    .addComponent(m_email)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel12))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(m_id)
                                    .addComponent(m_name)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel13))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(m_contact)
                                    .addComponent(m_fathername))))
                        .addGap(57, 57, 57))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(m_id, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(m_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(m_password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_batchNO, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_roll_no, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(m_course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(m_branch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_contact, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(m_fathername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 490, 690));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Name", "Email", "Password", "Gender", "Batch No", "Roll No", "Course", "Branch", "Content No", "Father Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 820, 570));

        btn_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        getContentPane().add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 30, 100, 30));
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 30, 180, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Manage Member");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String StudentID = m_id.getText();
        String Student_username = m_name.getText();
        String Student_email = m_email.getText();
        String Student_password = m_password.getText();
        String Student_gender = gender;
        String Student_BatchNo = m_batchNO.getText();
        String Student_RollNo = m_roll_no.getText();
        String Student_Course = (String) m_course.getSelectedItem();
        String Student_Branch = (String) m_branch.getSelectedItem();
        String Student_ContentNo = m_contact.getText();
        String Student_FatherName = m_fathername.getText();
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            st.executeUpdate("insert into student values('" + StudentID + "','" + Student_username + "','" + Student_email + "','" + Student_password + "','" + Student_gender + "','" + Student_BatchNo + "','" + Student_RollNo + "','" + Student_Course + "','" + Student_Branch + "','" + Student_ContentNo + "','" + Student_FatherName + "')");
            JOptionPane.showMessageDialog(null, "Successfully Added");
            load_Member();
            setVisible(false);
            new ManageMember().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Student ID allready exist");
//            setVisible(false);
//            new AddNewStudent().setVisible(true);

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void m_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_nameActionPerformed

    private void m_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_passwordActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        gender = "Female";
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        gender = "Male";
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void m_courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_courseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_courseActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Main().setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
        m_id.setText("");
        m_name.setText("");
        m_email.setText("");
        m_password.setText("");
        gender.isEmpty();
        m_batchNO.setText("");
        m_roll_no.setText("");
        m_contact.setText("");
        m_fathername.setText("");
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        DefaultTableModel D = (DefaultTableModel) jTable1.getModel();
        int selectIndex = jTable1.getSelectedRow();
        System.out.println(selectIndex);
        //m_id.setText(D.getValueAt(selectIndex,0).toString());
 
        String StudentID = m_id.getText();
        String Student_username = m_name.getText();
        String Student_email = m_email.getText();
        String Student_password = m_password.getText();
        String Student_gender = gender;
        String Student_BatchNo = m_batchNO.getText();
        String Student_RollNo = m_roll_no.getText();
        String Student_Course = (String) m_course.getSelectedItem();
        String Student_Branch = (String) m_branch.getSelectedItem();
        String Student_ContentNo = m_contact.getText();
        String Student_FatherName = m_fathername.getText();

        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            //pst = con.prepareStatement("update book set book_name=?,publisher=?,price=?,publish_year=?,edition=?, where bookID=?");
            pst = con.prepareStatement("UPDATE student SET Student_username=?,Student_email=?,Student_password=?,Student_gender=?,Student_BatchNo=?,Student_RollNo=?,Student_Course=?,Student_Branch=?,Student_ContentNo=?,Student_FatherName=? WHERE StudentID=?");

            pst.setString(1, Student_username);
            pst.setString(2, Student_email);
            pst.setString(3, Student_password);
            pst.setString(4, Student_gender);
            pst.setString(5, Student_BatchNo);
            pst.setString(6, Student_RollNo);
            pst.setString(7, Student_Course);
            pst.setString(8, Student_Branch);
            pst.setString(9, Student_ContentNo);
            pst.setString(10, Student_FatherName);
            pst.setString(11, StudentID);

            int k = pst.executeUpdate();
            if (k == 1) {
                JOptionPane.showMessageDialog(this, "Your Selected Member Details is Successfully Updated ");
                m_id.setText("");
                m_name.setText("");
                m_email.setText("");
                m_password.setText("");
                gender.isEmpty();
                m_batchNO.setText("");
                m_roll_no.setText("");
                m_course.setSelectedIndex(-1);
                m_branch.setSelectedIndex(-1);
                m_contact.setText("");
                m_fathername.setText("");
                load_Member();
            } else {
                JOptionPane.showMessageDialog(this, "Error");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel D = (DefaultTableModel) jTable1.getModel();
        int selectIndex = jTable1.getSelectedRow();

        m_id.setText(D.getValueAt(selectIndex, 0).toString());
        m_name.setText(D.getValueAt(selectIndex, 1).toString());
        m_email.setText(D.getValueAt(selectIndex, 2).toString());
        m_password.setText(D.getValueAt(selectIndex, 3).toString());
        //gender.setSelectItem(D.getValueAt(selectIndex,4).toString());
        gender = D.getValueAt(selectIndex, 4).toString();
        if (gender.equals("Male")) {
            jRadioButton2.setSelected(true);
        } else {
            jRadioButton3.setSelected(true);
        }

        m_batchNO.setText(D.getValueAt(selectIndex, 5).toString());
        m_roll_no.setText(D.getValueAt(selectIndex, 6).toString());
        m_course.setSelectedItem(D.getValueAt(selectIndex, 7).toString());
        m_branch.setSelectedItem(D.getValueAt(selectIndex, 8).toString());
        m_contact.setText(D.getValueAt(selectIndex, 9).toString());
        m_fathername.setText(D.getValueAt(selectIndex, 10).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel D = (DefaultTableModel) jTable1.getModel();
        int selectIndex = jTable1.getSelectedRow();
        //System.out.println(selectIndex);
        int StudentID = Integer.parseInt(D.getValueAt(selectIndex, 0).toString());

        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            //pst = con.prepareStatement("update book set book_name=?,publisher=?,price=?,publish_year=?,edition=?, where bookID=?");

            pst = con.prepareStatement("delete from student where StudentID=?");
            pst.setInt(1, StudentID);

            int k = pst.executeUpdate();

            if (k == 1) {
                JOptionPane.showMessageDialog(this, "Your Selected Member Is Successfully Deleted ");
                m_id.setText("");
                m_name.setText("");
                m_email.setText("");
                m_password.setText("");
                gender.isEmpty();

                m_batchNO.setText("");
                m_roll_no.setText("");
                m_course.setSelectedIndex(-1);
                m_branch.setSelectedIndex(-1);
                m_contact.setText("");
                m_fathername.setText("");
                load_Member();
            } else {
                JOptionPane.showMessageDialog(this, "Error");

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:

        String StudentID = search.getText();
        String Student_username = m_name.getText();
        String Student_email = m_email.getText();
        String Student_password = m_password.getText();
        String Student_gender = gender;
        String Student_BatchNo = m_batchNO.getText();
        String Student_RollNo = m_roll_no.getText();
        String Student_Course = (String) m_course.getSelectedItem();
        String Student_Branch = (String) m_branch.getSelectedItem();
        String Student_ContentNo = m_contact.getText();
        String Student_FatherName = m_fathername.getText();
        
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet RS = st.executeQuery("select * from student where StudentID='" + StudentID + "'");
            if (RS.next()) {
                StudentID = RS.getString("StudentID");
                m_id.setText(StudentID);
                Student_username = RS.getString("Student_username");
                m_name.setText(Student_username);
                Student_email = RS.getString("Student_email");
                m_email.setText(Student_email);
                Student_password = RS.getString("Student_password");
                m_password.setText(Student_password);

                gender = RS.getString("Student_gender");
                if (gender.equals("Male")) {
                    jRadioButton2.setSelected(true);
                } else {
                    jRadioButton3.setSelected(true);
                }
                Student_BatchNo = RS.getString("Student_BatchNo");
                m_batchNO.setText(Student_BatchNo);
                Student_RollNo = RS.getString("Student_RollNo");
                m_roll_no.setText(Student_RollNo);
                Student_Course = RS.getString("Student_Course");
                //m_course.setSelectedIndex();
                switch (Student_Course) {
                    case "Pre-HND":
                        m_course.setSelectedIndex(0);
                        break;
                    case "HNC":
                        m_course.setSelectedIndex(1);
                        break;
                    case "HND":
                        m_course.setSelectedIndex(2);
                        break;
                    case "BSC":
                        m_course.setSelectedIndex(3);
                        break;
                    case "BSC(Honas)":
                        m_course.setSelectedIndex(4);
                        break;
                    case "BSC(Master)":
                        m_course.setSelectedIndex(5);
                        break;
                    case "BSC(PHD)":
                        m_course.setSelectedIndex(6);
                        break;
                }
                Student_Branch = RS.getString("Student_Branch");
                m_branch.setSelectedIndex(1);
                switch (Student_Branch) {
                    case "Programming":
                        m_branch.setSelectedIndex(0);
                        break;
                    case "Networking":
                        m_branch.setSelectedIndex(1);
                        break;
                }
                Student_ContentNo = RS.getString("Student_ContentNo");
                m_contact.setText(Student_ContentNo);
                Student_FatherName = RS.getString("Student_FatherName");
                m_fathername.setText(Student_FatherName);

//                m_id.setText(RS.getString(1));
//                m_name.setText(RS.getString(2));
//                m_email.setText(RS.getString(3));
//                m_password.setText(RS.getString(4));
//                gender = RS.getValueAt(selectIndex,4).toString();
//                gender.setText(RS.getString(gender));
//                if(gender.equals("Male")){
//                 jRadioButton2.setSelected(true);
//                }
//                else{
//                jRadioButton3.setSelected(true);
//                }
//
//                m_batchNO.setText(RS.getString(6));
//                m_roll_no.setText(RS.getString(7));
//                m_course.setSelectedIndex(8);
//                m_branch.setSelectedIndex(9);
//                m_contact.setText(RS.getString(10));
//                m_fathername.setText(RS.getString(11));
//                m_id.setEditable(false);
//                m_name.setEditable(false);
            } else {
                JOptionPane.showMessageDialog(null, "Book is not issued to this student");
                setVisible(false);
                new ManageMember().setVisible(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageMember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField m_batchNO;
    private javax.swing.JComboBox<String> m_branch;
    private javax.swing.JTextField m_contact;
    private javax.swing.JComboBox<String> m_course;
    private javax.swing.JTextField m_email;
    private javax.swing.JTextField m_fathername;
    private javax.swing.JTextField m_id;
    private javax.swing.JTextField m_name;
    private javax.swing.JPasswordField m_password;
    private javax.swing.JTextField m_roll_no;
    private javax.swing.JTextField search;
    // End of variables declaration//GEN-END:variables
private String gender;
}
